### ISSUE TITLE
Library failed to install

### ISSUE THREAD

**Issue by laszlo1337** [primecodecom/async-qrcode-generator#1]
Hello. I cannot install this library, here's the error:

NodeJS version: 18.12
OS: W10
npm: 8.19.2

```
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.12.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.3 found at "C:\Python311\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.12.0/node-v18.12.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.12.0/node-v18.12.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v18.12.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v18.12.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v18.12.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v18.12.0/win-arm64/node.lib
npm ERR! gyp http 404 https://nodejs.org/download/release/v18.12.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.12.0/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.12.0/win-x86/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v18.12.0/SHASUMS256.txt
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (D:\SDK\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at D:\SDK\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\SDK\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
npm ERR! gyp ERR! stack     at D:\SDK\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at D:\SDK\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:385:16
npm ERR! gyp ERR! stack     at D:\SDK\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at D:\SDK\nvm\v18.12.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "D:\\SDK\\nodejs\\node.exe" "D:\\SDK\\nvm\\v18.12.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\Projects\xxx-sveltekit\node_modules\@primecode\async-qrcode
npm ERR! gyp ERR! node -v v18.12.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
```

I assume this is because this library requires bunch of stuff completely unrelated to NodeJS?

Is there a possibility of releasing a self-containing package? 
If not, do you know if there are other NodeJS libraries which can do QR code styling?

Cheers!

**Comment by servo98** [comment]
Same here, I'll try installing Windows Visual Studio C+ Library
